server:
  port: 8765

spring:
  application:
    name: edge-service

zuul:
  ignoredServices: "*"
  routes:
    order-service:
      sensitiveHeaders:
      path: /order/**
      serviceId: order-service
      stripPrefix: false
    item-service:
      sensitiveHeaders:
      path: /items/**
      serviceId: item-service
      stripPrefix: false
    test-service:
      sensitiveHeaders:
      path: /test/**
      serviceId: test-service
      stripPrefix: true

test-service:
  ribbon:
    listOfServers: https://httpbin.org/
    
logging.level.org.springframework: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'
